### ISSUE TITLE
Add HTTP Header to Http Configuration retriever

### ISSUE THREAD

**Issue by ukr15** [vert-x3/vertx-config#102]
In case a configuration object should be retrieved from a REST service requesting a application-specific content type, it must be possible to add this header parameters to the server specification, e.g. by an additional attribute headers with MultiMap as value.

Otherwise, a  a io.vertx.core.json.DecodeException is thrown due to the 415 Unsupported Media Type error.

**Comment by gaol** [comment]
This should be easy to fix, I will try to make a PR for this.

**Comment by vietj** [comment]
thanks @gaol
