### ISSUE TITLE
ConfigRetriever doesn't load properties file + small typo in factory name

### ISSUE THREAD

**Issue by peetboy** [vert-x3/vertx-config#122]
### Version
4.0.0.CR1
### Context
I have a verticle with example code for loading properties from documentation but nothing is loaded.

resources/conf/raw.properties
```
server.host=localhost
server.port=8080
multiple.values=1,2,3
```
code in verticle
```
ConfigStoreOptions propertyWithRawData = new ConfigStoreOptions()
    .setFormat("properties")
    .setType("file")
    .setConfig(new JsonObject().put("path", "conf/raw.properties").put("raw-data", true).put("hierarchical", true)
    );

ConfigRetriever configRetriever = ConfigRetriever.create(vertx, new ConfigRetrieverOptions().addStore(propertyWithRawData));
```
After handling of configRetriever.getConfig() the result is empty.

I do have another configuration config.json in resources/conf folder and that one is loaded properly by default.
I have also tried with Directory config store and "*.properties" pattern but with no luck.

Also during investigation I found a typo in **io.vertx.config.impl.spi.FileConfigtoreFactory** (missing 'S').

**Comment by mikand13** [comment]
I have a similar issue. After upgrading to 4.0.0, the configRetriever is no longer able to read and load to cache my application.yaml.

ie this:

`
    @Bean
    fun configStore(): ConfigRetriever {
        val store = configStoreOptionsOf(
            type = "file",
            format = "yaml",
            config = jsonObjectOf(
                "path" to "application.yml"
            )
        )
        return create(vertx, configRetrieverOptionsOf(stores = listOf(store)))
    }
`

now leads to this:

`
api_1                   | 2020-12-23 13:31:16,640 [-thread-0] ERROR io.vertx.config.impl.ConfigRetrieverImpl  - Error while scanning configuration
api_1                   | java.nio.file.NoSuchFileException: .vertx-5dff7692-10f4-4fd3-a381-b0ec54b36472/application.yml
api_1                   | 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[na:na]
api_1                   | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
api_1                   | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[na:na]
api_1                   | 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219) ~[na:na]
api_1                   | 	at java.base/java.nio.file.Files.newByteChannel(Files.java:370) ~[na:na]
api_1                   | 	at java.base/java.nio.file.Files.newByteChannel(Files.java:421) ~[na:na]
api_1                   | 	at java.base/java.nio.file.Files.readAllBytes(Files.java:3205) ~[na:na]
api_1                   | 	at io.vertx.core.file.impl.FileSystemImpl$16.perform(FileSystemImpl.java:1041) ~[vertx-core-4.0.0.jar!/:4.0.0]
api_1                   | 	... 11 common frames omitted
api_1                   | Wrapped by: io.vertx.core.file.FileSystemException: java.nio.file.NoSuchFileException: .vertx-5dff7692-10f4-4fd3-a381-b0ec54b36472/application.yml
api_1                   | 	at io.vertx.core.file.impl.FileSystemImpl$16.perform(FileSystemImpl.java:1045) ~[vertx-core-4.0.0.jar!/:4.0.0]
api_1                   | 	at io.vertx.core.file.impl.FileSystemImpl$16.perform(FileSystemImpl.java:1037) ~[vertx-core-4.0.0.jar!/:4.0.0]
api_1                   | 	at io.vertx.core.file.impl.FileSystemImpl$BlockingAction.handle(FileSystemImpl.java:1149) ~[vertx-core-4.0.0.jar!/:4.0.0]
api_1                   | 	at io.vertx.core.file.impl.FileSystemImpl$BlockingAction.handle(FileSystemImpl.java:1131) ~[vertx-core-4.0.0.jar!/:4.0.0]
api_1                   | 	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:179) ~[vertx-core-4.0.0.jar!/:4.0.0]
api_1                   | 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96) ~[vertx-core-4.0.0.jar!/:4.0.0]
api_1                   | 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:177) ~[vertx-core-4.0.0.jar!/:4.0.0]
api_1                   | 	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[vertx-core-4.0.0.jar!/:4.0.0]
api_1                   | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
api_1                   | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
api_1                   | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.53.Final.jar!/:4.1.53.Final]
api_1                   | 	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
`

Worked fine for all CR versions.

**Comment by vietj** [comment]
can you provide a reproducer project for this ?

**Comment by mikand13** [comment]
Doing some testing atm. With further research it seems to work fine in normal circumstances but breaks within a docker container. Might be a file system issue i guess, but there has been no change to the image. Will investigate more.

**Comment by ClaudenirFreitas** [comment]
Hi @peetboy @mikand13 ,

I've just created [this project](https://github.com/ClaudenirFreitas/vertx-config-122) to validate this issue and it's working fine to me... could you check please?

Cheers.

**Comment by peetboy** [comment]
Tested and now it really is working fine for me as well. I don't know what was the issue then. But at least the typo can be fixed, right? :)

**Comment by vietj** [comment]
Typo fixed https://github.com/vert-x3/vertx-config/commits/master

**Comment by vietj** [comment]
I'll fix this as invalid as it could not be reproduced

**Comment by mikand13** [comment]
Sounds like a plan. I have not been able to replicate outside of the docker environment either. It is curious that this only appeared after i promoted from CR to release though. No other changes were made 🤔 

I ended up converting from a .yml filebased solution to just reading out the spring env as json and pushing it into the configretriever that way. Not what I was looking for but it solves the immediate issue.

Is there any plan for .properties in-memory support @vietj ? ie loading the env like this:

```kotlin
    @ConfigurationProperties(prefix = "")
    @Bean
    fun getEnvironmentProperties(): Properties = Properties()
```

And doing something like this:

```kotlin
    @Bean
    fun configStore(getEnvironmentProperties: Properties): ConfigRetriever {
        val store = configStoreOptionsOf(
            format = "properties",
            config = jsonObjectOf(
                "props" to getEnvironmentProperties
            )
        )

        return create(vertx, configRetrieverOptionsOf(stores = listOf(store)))
    }
```

**Comment by vietj** [comment]
@mikand13 not formally but any kind of contribution is welcome on this project, we will review PR's or we are also pleased having new maintainers on this project
