### ISSUE TITLE
JavaScript, Kotlin, Groovy and Ruby config documentation not available

### ISSUE THREAD

**Issue by prasanthatl** [vert-x3/vertx-config#137]
### Questions

Documentation links for JavaScript, Kotlin, Groovy and Ruby are not working. It looks like documentation for this was available in previous versions(ex: 3.5), but it has been removed intentionally or accidently in the master version. Please correct the links or delete them.

### Version

master branch

### Context

I encountered an exception which looks suspicious while ...

### Do you have a reproducer?

Click on the links on the README.adoc at project root level.

### Steps to reproduce

Click on the links(JavaScript or Kotlin or Groovy or Ruby documentation) on the README.adoc at project root level.

**Comment by vietj** [comment]
this is expected.

- Kotlin and Groovy developer can use the Java version
- JavaScript developer should migrate to https://reactiverse.io/es4x/ project
- Ruby has been dropped in Vert.x 4 due to the lack of interest
