### ISSUE TITLE
support CONFIG_FORCE_ environment variables with HOCON config file format

### ISSUE THREAD

**Issue by nareshv** [vert-x3/vertx-config#143]
#### Describe the feature

typesafe config supports overriding the config key/value pairs using environment variables using CONFIG_FORCE_ mechanism

Reference: https://github.com/lightbend/config#optional-system-or-env-variable-overrides

#### Use cases

This will enable overriding configurations using the typesafe config way.

#### Contribution

As vert.x supports both ENV & HOCON formats, not sure where this feature will go. After exploring the ENV config engine, SYS config engine found out that there are some features in the SYS engine (hierarchical=true) can be useful in ENV engine and HOCON + ENV engine as well.

Open for suggestions and direction on this ?

**Comment by gaol** [comment]
I think this can be done in HoconProcessor with a specified flag to respect overridden environment variables or not.
