### ISSUE TITLE
Preventing 'EnvVariablesConfigStore' from attempting to convert values.

### ISSUE THREAD

**Issue by brunomcustodio** [vert-x3/vertx-config#16]
The [`EnvVariablesConfigStore`](https://github.com/vert-x3/vertx-config/blob/master/vertx-config/src/main/java/io/vertx/config/impl/spi/EnvVariablesConfigStore.java#L46) attempts a number of conversions on the values of envvar values before making them available to the `config.getXXX` methods. For instance, if I define

```
CLIENT_ID="162738491282"
```

as one of my environment variables it will end up in `config()` as a `Double` instead of a `String`. This happens because `EnvVariablesConfigStore` uses [`JsonObjectHelper#put`](https://github.com/vert-x3/vertx-config/blob/master/vertx-config/src/main/java/io/vertx/config/spi/utils/JsonObjectHelper.java#L21) on the set of envvars. However, sometimes all you need are the "raw" string values. Also, if you are later querying these with methods like `config().getDouble()` and `config().getString()`, I see little to no point in this behaviour—`config().getString("CLIENT_ID")` will throw in this use case.

Could we get one of the following?

1. Make `EnvVariablesConfigStore` not use `JsonObjectHelper#put` and get raw values in `config()`.
2. Introduce a `RawEnvVariablesConfigStore` in order not to break any existing code out there and still get raw values in `config()`?

In any of the cases, would you consider a PR?

**Comment by cescoffier** [comment]
I may be wrong, but can't you get the number from JSON as a String:

```
Double.toString(config.getDouble("key", 2.0));
```

**Comment by cescoffier** [comment]
That's said, we can add an option to the Env and Sys config stores to not parse the content (read all entries as String). Something like `'json-conversion': false'

**Comment by brunomcustodio** [comment]
@cescoffier that wouldn't work—you may end up with something like `"4.31543975932E11"`. Even if it wasn't the case, that would only work as long as the value stored in the envvar doesn't overflow (I'm thinking of big numerical strings).

**Comment by cescoffier** [comment]
@brunomcustodio if the string representation is not a valid Java double, it will be added as a String to the json object.

**Comment by brunomcustodio** [comment]
@cescoffier yes, I know, but I was talking specifically about your snippet :-)

**Comment by brunomcustodio** [comment]
Let's perhaps continue this on #17.
