### ISSUE TITLE
ConfigRetrieverImpl calls getConfig() in its constructor

### ISSUE THREAD

**Issue by informedgut** [vert-x3/vertx-config#23]
ConfigRetrieverImpl calls getConfig(), and with an empty handler at that. Clement agreed in the Google group that it should be taken out.  Let the application call getConfig() explicitly.

Thanks!
Iggy

**Comment by informedgut** [comment]
Oh while you're at it, and let me know if you'd prefer that I create a separate issue for this, please see if you can figure out a way to allow us to configure the Vertx object itself (VertxOptions) using properties from the config store(s).  I had to jump through hoops to make it happen.  It's the chicken-or-egg issue I refer to in the Google group.  It needs a Vertx instance but I want the Vertx instance to use the config, too.  I had to create two ConfigRetrievers - The first one does the retrieving using a temp Vertx object.  Then, I create the final Vertx object and feed it into the second and final ConfigRetriever.  This led me to filing this issue.  I didn't want my second retriever to do another retrieve.

Not sure if there's a solution to this chicken-or-egg issue.  But thought I'd bring it up.

**Comment by cescoffier** [comment]
@informedgut yes, please create another issue for this. It's a tricky issue as the config retriever needs `vertx`. Are you looking for configuring vert.x itself or the verticle?

**Comment by informedgut** [comment]
Thanks, Clement.  Created issue #24 for it.
