### ISSUE TITLE
Allow configuring of the Vertx instance itself

### ISSUE THREAD

**Issue by informedgut** [vert-x3/vertx-config#24]
I don't know how you'd pull this off since Vertx Config requires a Vertx Instance, hence the chicken-or-egg situation.  What I've done as a workaround is have an initial ConfigRetriever that uses a temp Vertx instance.  It does the initial retrieve and then I configure Vertx using the properties from there. Then, I close the ConfigRetriever and create a new one that uses the new and configured Vertx instance.  It's the one used for subsequent retrievals, both manual and auto-scans.

Thanks and good luck. :)

(This is a follow-up to #23.)

**Comment by cazacugmihai** [comment]
You can extend [Launcher](https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/Launcher.java), load the configuration (e.g.: a yaml config file) and inject it into Vertx configuration but it looks more like a hack. It would be nice to have this behavior supported by the Vertx itself.

**Comment by InfoSec812** [comment]
@cazacugmihai Except to use the ConfigRetriever you need an instance of Vertx. For the methods in Launcher where the Vertx instance is available, there is no way to set the config directly. You would have to use something like:

```
vertx.getOrCreateContext().config().mergeIn(newConfig);
```

But that COULD be problematic depending on how you are starting/configuring your application.

**Comment by cescoffier** [comment]
The configuration has been updated with an example.
