### ISSUE TITLE
redis config - Retrieve json value - WRONGTYPE Operation against a key holding the wrong kind of value

### ISSUE THREAD

**Issue by Sergey80** [vert-x3/vertx-config#28]
In redis-cli:

```
    127.0.0.1:6379> get my-microservice-config
    "{\n "http.port": 35001\n}\n"
```

(the way I set it is [from the bash-script][1]: `redis-cli -x set my-config < my-microservice-config.json` ) where the my-microservice-config.json hold the json configuration.  

In the code where I use `vertx-config`:

```
    final ConfigStoreOptions redisSore = new ConfigStoreOptions()
    .setType("redis")
    .setConfig(new JsonObject()
    .put("host", "localhost")
    .put("port", 6379)
    .put("key", "my-microservice-config")
    );

    final ConfigRetriever retriever = ConfigRetriever.create(vertx, options);
    retriever.getConfig( ar -> {
    if ( ar.failed()) {
    System.out.println("Failed to retrieve the configuration");
```

...

got error: 

> WRONGTYPE Operation against a key holding the wrong kind of value

 checking the type of the value: it looks pretty much like **string type**

```
    127.0.0.1:6379> type my-microservice-config
    string
```

but anyways.. **the question is**: how to retrieve the config value that I see in cli when I do get ?

  [1]: https://stackoverflow.com/questions/47368364/set-json-value-from-file-to-redis
  [2]: https://redis.io/topics/data-types-intro

**Comment by Sergey80** [comment]
Hmm.. actually I can not understand why it is **int**:

127.0.0.1:6379> exists my-microservice-config
(integer) 1
127.0.0.1:6379> get my-microservice-config
"{\n    \"http.port\": 35001\n}\n"

**Comment by Sergey80** [comment]
well I see now why: github.com/vert-x3/vertx-config/blob/master/vertx-config-red‌​is/… 

hgetall my-microservice-config (error) WRONGTYPE Operation against a key holding the wrong kind of value. I can not say it is nice though. I would love to get my json as I set it.

**Comment by cescoffier** [comment]
It's a limitation in the vert.x redis client. Can you open an issue on the project so we can add this support.

**Comment by cescoffier** [comment]
Closing this issue as it's a Redis client issue.

**Comment by pmlopes** [comment]
@Sergey80 `hgetall` returns a `multi bulk` while you're storing a `bulk`. 

See: https://redis.io/commands/hgetall
