### ISSUE TITLE
Listening to the changes in redis

### ISSUE THREAD

**Issue by Sergey80** [vert-x3/vertx-config#29]
I would expect that this could that listens to the `my-microservice-config`'s values

Here I 
1. create a redis store 
2. configure retrive options (every 2 sec). 
3. set the options to the retriver

Then if I change a value for the `my-microservice-config` then it would trigger the  System.out.ptintln("123") output.

This seems does not work.

Also (speaking about ConfigStoreOptions abstraction) seems we may not use  .setScanPeriod(2000) since it come with pub-sub capabilities already so it would notify as it is changed.

Here is the code I use to test it:
 ```
final ConfigStoreOptions redisSore = new ConfigStoreOptions()
            .setType("redis")
            .setConfig(new JsonObject()
                .put("host", "localhost")
                .put("port", 6379)
                .put("key", "my-microservice-config")
            );

        final ConfigRetrieverOptions options = new ConfigRetrieverOptions()   // listen to the config changes
            .setScanPeriod(2000)
            .addStore(redisSore);

        final ConfigRetriever retriever = ConfigRetriever.create(vertx, options);
        retriever.getConfig( ar -> {
            if ( ar.failed()) {

                } else {
                System.out.ptintln("123");  // never reach this after value change
                final JsonObject jsonConfig = ar.result();
```

**Comment by cescoffier** [comment]
It should work, do you have a reproducer?

**Comment by Sergey80** [comment]
Will prepare it today.

**Comment by cescoffier** [comment]
Ping @Sergey80

**Comment by cescoffier** [comment]
Close due to inactivity. Please reopen if you still have the issue.
