### ISSUE TITLE
directory configurations load does not load file contents

### ISSUE THREAD

**Issue by tomicse** [vert-x3/vertx-config#30]
Hi, I tried with different paths (for type directory), but I could not achieve to load .json or .properties files for a given path. 
It works without exception, the result Map(I am not sure, if it is map) is empty.

**Comment by cescoffier** [comment]
Can you provide a reproducer?

**Comment by tomicse** [comment]
Hi, I used the code from example or from description with addition of .conf, but I tried without .conf too.
I tried then config directory move to another places to check, if I perhaps path not right defined.
I played with ("path", "resources/config") too, always the same Problem, Empty result. 
In file I used normal property syntax: e.g. level.max_user_number=20
        ConfigStoreOptions dir = new ConfigStoreOptions()
                .setType("directory")
                .setConfig(new JsonObject().put("path", "resources/config")
                        .put("filesets", new JsonArray()
                                .add(new JsonObject().put("pattern", "dir/*json"))
                                .add(new JsonObject().put("pattern", "dir/*.properties")
                                        .put("format", "properties"))
                                .add(new JsonObject().put("pattern", "dir/*.conf")
                                        .put("format", "properties"))
                        ));

**Comment by tomicse** [comment]
Already works. Problem was, that I have config files under src/main/resources/config directory,
if I use .setType("directory").setConfig(new JsonObject().put("path", "src/main/resources/config")
...it works, if I use .setType("directory").setConfig(new JsonObject().put("path", "config"), does not work. Is this a problem with classpath?

**Comment by cescoffier** [comment]
Yes, it's a problem with the classpath. The `path` is considered relative to the `CWD` (current working directory). In your IDE it's often the project root.

**Comment by cescoffier** [comment]
Close as reported by the user.
