### ISSUE TITLE
Missing license headers

### ISSUE THREAD

**Issue by msrb** [vert-x3/vertx-config#32]
Hello,

I noticed that most of the .java files in this repo are missing license headers. There is no SCM URL in pom.xml files and <licenses> tag is also missing from there. This all combined means that people who get these vertx (source-)artifacts from Maven Central need to google what the license might be, or where this repository is.

**Comment by cescoffier** [comment]
I believe it's the case for most Vert.x module.

About license header, @jponge  is working on adding them.
I will add the SCM metadata and license in the pom.xml file. Notice that the LICENSE file is present in the repository.

**Comment by cescoffier** [comment]
@msrb I've added the missing metadata and license headers.

@vietj  Do you know if the `<tag>HEAD</tag>` is updated during our release process?

**Comment by vietj** [comment]
sorry missed the notification, what is HEAD tag ? javadoc ?

**Comment by cescoffier** [comment]
Everything has been fixed. Closing.
