### ISSUE TITLE
Add a "raw-data" option for processing properties files

### ISSUE THREAD

**Issue by jessym** [vert-x3/vertx-config#38]
This is already implemented for Environment Variables. From the [documentation](http://vertx.io/docs/vertx-config/java/#_environment_variables):

> ... By default, the retrieved value are transformed into JSON compatible structures (number, string, boolean, json object and json array). To avoid this conversion, configure the raw-data attribute:
> ```
> ConfigStoreOptions json = new ConfigStoreOptions()
>   .setType("env")
>   .setConfig(new JsonObject().put("raw-data", true));
> ```

For example, I have an API key in my properties file which looks like this
```
6134789540453672
```
But it is read like `Integer.MAX_VALUE` for some reason
```
2147483647
```
which could be avoided if there was an option to read all values as strings.

**Comment by cescoffier** [comment]
I've added the feature for system properties and property files. The doc has been updated.
