### ISSUE TITLE
Adding multiple file stores generates a wrong JsonObject

### ISSUE THREAD

**Issue by ufoscout** [vert-x3/vertx-config#47]
In my project I have two config files (one for application configuration and the other for tests):

config.json:
```json
{
  "server": {
    "port": 8080
  },
  "jwt": {
    "secret": "mySecret",
    "signatureAlgorithm": "HS512",
    "tokenValidityMinutes": 600
  }
}
```

test-config.json:
```json
{
  "server": {
    "port": 0
  }
}
```

They are loaded this way (kotlin code):
```kotlin
val fileStore = ConfigStoreOptions()
         .setType("file")
         .setOptional(false)
         .setConfig(JsonObject().put("path", "conf/config.json"))

val testFileStore = ConfigStoreOptions()
        .setType("file")
        .setOptional(true)
        .setConfig(JsonObject().put("path", "conf/test-config.json"))

var retriever = ConfigRetriever.create(vertx, ConfigRetrieverOptions().addStore(fileStore).addStore(testFileStore))
```

If I do not add the testFileStore to the ConfigRetrieverOptions(), everything works fine and the generated JsonObject is:
```json
{"server":{"port":8080},"jwt":{"secret":"mySecret","signatureAlgorithm":"HS512","tokenValidityMinutes":600}}
```

But, when I add the testFileStore then the JsonObject is wrong:
```json
{"server":{"map":{"port":0},"empty":false},"jwt":{"secret":"mySecret","signatureAlgorithm":"HS512","tokenValidityMinutes":600}}
```

Please note that the error can be reproduced by simply adding two times the same file. For example this code:
```kotlin
val fileStore = ConfigStoreOptions()
        .setType("file")
        .setOptional(false)
        .setConfig(JsonObject().put("path", "conf/config.json"))

var retriever = ConfigRetriever.create(vertx, ConfigRetrieverOptions().addStore(fileStore).addStore(fileStore))
```

generates this wrong JsonObject:
```json
{"server":{"map":{"port":8080},"empty":false},"jwt":{"map":{"secret":"mySecret","signatureAlgorithm":"HS512","tokenValidityMinutes":600},"empty":false}}
```

**Comment by cescoffier** [comment]
Looking into it.

**Comment by cescoffier** [comment]
@ufoscout I've tried to reproduce it in Java and in Kotlin but failed. Can you provide a reproducer?

**Comment by vietj** [comment]
@ufoscout would you mind try this on your mappers:

```
    // custom types
    module.addSerializer(JsonObject.class, new JsonObjectSerializer());
    module.addSerializer(JsonArray.class, new JsonArraySerializer());
    // he have 2 extensions: RFC-7493
    module.addSerializer(Instant.class, new InstantSerializer());
    module.addSerializer(byte[].class, new ByteArraySerializer());
```

and see if that fixes the problem ?

**Comment by ufoscout** [comment]
@vietj 
Yes, indeed adding those serializers fixes the issue. However, they are declared as private into the Json class, so there is no way to reuse them.
Nevertheless, I found a better solution. In fact, instead of overriding the Json mappers I can extend adding the KotlinModule:
```kotlin
        Json.mapper.registerModule(KotlinModule())
        Json.prettyMapper.registerModule(KotlinModule())
```
This is more maintainable and works as expected.
Probably this should be reported somewhere in the kotlin support documentation.

**Comment by vietj** [comment]
@ufoscout thanks for reporting, I think actually we will add documentation in vertx-core as this is a not only kotlin issue.

**Comment by ufoscout** [comment]
@vietj 
Why do you have a custom serializer for the Instant class? Shouldn't you instead register the JavaTimeModule provided by Jackson?

**Comment by vietj** [comment]
@ufoscout I think @pmlopes can elaborate on it

**Comment by cescoffier** [comment]
Closing this issue, not related to vert.x config.
