### ISSUE TITLE
java.lang.NoClassDefFoundError: io/vertx/lang/groovy/ConversionHelper

### ISSUE THREAD

**Issue by cazacugmihai** [vert-x3/vertx-config#5]
Hi,

I'm using `vertx-config` and `vertx-config-yaml` modules in my app and, _sometimes_, when the application starts, I've got this error:

```
java.lang.NoClassDefFoundError: io/vertx/lang/groovy/ConversionHelper
```

It seems that the class is part of `vertx-lang-groovy` and I don't have it in my class path (I didn't add it because I don't use it - at least, directly).

The question is: is it mandatory to add this module in order to use the two other ones? And, why it works sometimes? 

Thanks!  

Environment:
- java 1.8.0_121-b13
- vertx-core 3.4.0-SNAPSHOT
- vertx-config 3.4.0-SNAPSHOT
- vertx-config-yaml 3.4.0-SNAPSHOT

**Comment by cescoffier** [comment]
@vietj do you know why we could have this ?

I will try to come up with a reproducer.

**Comment by vietj** [comment]
it could be that the user has not vertx-lang-groovy in the classpath but still has the Groovy jar that loads the groovy extension.

**Comment by cazacugmihai** [comment]
Yes, the `groovy-all` jar is present in my classpath but I think that I should't be forced to add an extra dependency (`vertx-lang-groovy`) in case of using  `vertx-config`.

**Comment by vietj** [comment]
@cazacugmihai we don't enforce you to do so, let us find a better solution to that

**Comment by vietj** [comment]
I beleive that the ConversionHelper code is small and generic enough to be moved somewhere in Vert.x core

**Comment by vietj** [comment]
and the problem it tries to solve is converting object / object in a generic manner

**Comment by vietj** [comment]
well it does reference gstring :)

**Comment by vietj** [comment]
but gstring is CharSequence

**Comment by cazacugmihai** [comment]
I'm sure that this was not done intentionally. Thanks for your investigation!

**Comment by vietj** [comment]
nope, another way is to use an extension factory that tries to load the various classes

**Comment by vietj** [comment]
but anyway just stay tuned in this thread and be ready to try a solution to confirm it's cool for you

**Comment by cazacugmihai** [comment]
Sure. I'll be waiting for it. Thanks!

**Comment by vietj** [comment]
@cazacugmihai can you give a try ? now the generated code should not need vertx-lang-groovy anymore. I've pushed new snapshots for `vertx-config` (the CI should deploy new snapshots also at some point).

**Comment by cazacugmihai** [comment]
I'm trying right now.

**Comment by cazacugmihai** [comment]
Everything works fine now. Thanks!
