### ISSUE TITLE
Spring Config Server: wrong overriding order

### ISSUE THREAD

**Issue by jpiecuch** [vert-x3/vertx-config#54]
I've recently used lib for obtaining configuration from Spring Config Server and I think that there is critical bug in there. Basically properties overriding order is wrong. Spring uses order described here [https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html).

Spring Config Server when calling for configuration returns collection of _propertySources_  in descending order (most relevant first). In your code you are merging those sources but in the way that properties from the next source override those from previous.

I've fixed this issue for my local development so if you need more clarification I can provide code snippet or even pull request.

**Comment by cescoffier** [comment]
Hi, nice catch. A PR would be great!

**Comment by jpiecuch** [comment]
Awesome, one other thing. Spring provide functionality to expose configuration in JSON format by calling URI /{application}-{profile}.json. By default it also resolves Spring specific placeholders (it can be disabled by provding parameter resolvePlaceholder=false). It's explained here: [https://cloud.spring.io/spring-cloud-config/multi/multi__serving_alternative_formats.html](url). I believe it would be significant improvement if vert.x would be able to consume those additional format.

Do you think it's worth to add this functionality to PR too?

**Comment by cescoffier** [comment]
Yes, definitely!

**Comment by jpiecuch** [comment]
PR ready.

**Comment by jpiecuch** [comment]
Problem solved.
