### ISSUE TITLE
Missing unit in documentation of scanPeriod in ConfigRetrieverOptions

### ISSUE THREAD

**Issue by FrodeI** [vert-x3/vertx-config#61]
The API documentation should specify that the unit of scanPeriod in ConfigRetrieverOptions is ms so developers don't have to search the source code to verify this.

https://vertx.io/docs/apidocs/io/vertx/config/ConfigRetrieverOptions.html#setScanPeriod-long-

**Comment by cescoffier** [comment]
Fixed in master! Thanks for reporting, the whole class was missing the javadoc.
