### ISSUE TITLE
Can't use multiple stores

### ISSUE THREAD

**Issue by pgh70** [vert-x3/vertx-config#65]
Unable to use multiple stores in java:

Using "vault" and "redis" gives: "(known implementations are: [redis])" if redis is first in dependencies and "(known implementations are: [vault])" if vault is first. Can't use them both.

Even when using only one additional store an error is thrown when using the "json" config store. It seems like an additional store is overwriting the available stores.

**Comment by cescoffier** [comment]
Check that the META-INF/services files contain all the stores you want to use.

**Comment by pgh70** [comment]
Me bad... I did forget:

    mergeServiceFiles {
        include 'META-INF/services/io.vertx.core.spi.VerticleFactory'
    }

in my build.gradle shadowJar section...
A pointer this requirement in the documentation would be nice...
