### ISSUE TITLE
Be able to parse Consul values on read

### ISSUE THREAD

**Issue by Addvilz** [vert-x3/vertx-config#71]
It would be really useful to be able to parse Consul KV values as rich data (JSON, YML) on the fly instead of always using String value. 

`ConsulConfigStore:80` for reference.

I can do a PR.

**Comment by romanpierson** [comment]
Hi @Addvilz 
I just wanted to open such an issue as well and saw you already did. Do you have an idea what's the status of this, could this be merged into the standard? As it would be really useful.

**Comment by Addvilz** [comment]
No idea. I worked around it manually deserializing.

**Comment by Addvilz** [comment]
@vietj ... that did not mean however that this request would not be useful.
