### ISSUE TITLE
[Feature Request] Add support for HashiCorp's Vault

### ISSUE THREAD

**Issue by vadimvera** [vert-x3/vertx-config#8]
It would be nice to have the possibility to retrieve some configuration/settings (more likely: *secrets*) from HashiCorp's [Vault](https://www.hashicorp.com/products/vault/).

> Vault can manage static and dynamic secrets such as username/password for remote applications/resources and provide credentials for external services such as MySQL, PostgreSQL, Apache Cassandra, MongoDB, Consul, AWS and more.

Maybe a new `Configuration store`?

**References:** The Spring guys have something similar in the [Spring Cloud](https://github.com/spring-cloud/spring-cloud-vault) "umbrella".

**Comment by cescoffier** [comment]
PR submitted: https://github.com/vert-x3/vertx-config/pull/15

**Comment by cescoffier** [comment]
PR merged.
