### ISSUE TITLE
ArrayIndexOutOfBoundsException while reading hierarchical properties file with comments

### ISSUE THREAD

**Issue by akuznetsov-gridgain** [vert-x3/vertx-config#81]
See [SO] (https://stackoverflow.com/questions/54501961/vert-x-config-exception-while-reading-properties-file-with-comments).

I investigated a little.

I think the problem is that "HierarchicalPropertiesReader.toJson()" does not expect that incoming line can be in other format that "key=val".

FlatPropertiesReader read properties via "java.util.Properties.load()" that knows how to deal with comments.

But HierarchicalPropertiesReader reads properties directly from file: "new BufferedReader(new InputStreamReader(byteStream))".

I think HierarchicalPropertiesReader should also read properties via "java.util.Properties.load()".

**Comment by SINGS079** [comment]
I think even this is resolved 
https://github.com/vert-x3/vertx-config/blob/cea99b55c9186ff65f7b3cbeaeff0202dad59739/vertx-config/src/main/java/io/vertx/config/impl/spi/PropertiesConfigProcessor.java#L117
@akuznetsov-gridgain Can you please verify it.

**Comment by akuznetsov-gridgain** [comment]
> @akuznetsov-gridgain Can you please verify it.
I would like, but I can't, because we dropped Vertex in favor of Spring Boot.
Sorry.

**Comment by ClaudenirFreitas** [comment]
It's working in version `4.0.0-milestone5` and `4.0.0.Beta1`, I tested.
I think that next version `4.0.0` this issue will be solved.

**Comment by vietj** [comment]
did you check with 3.9 @ClaudenirFreitas ?

**Comment by ClaudenirFreitas** [comment]
Yes, I did @vietj ! It isn't working with `3.9.2` because the changes were applied in `4.0.0.Beta1`. Check it out: [commit](https://github.com/vert-x3/vertx-config/commit/a1ba8cea40f647f0fa595a103d49677b49258127#diff-a343a368d98b0f8711a943245b627cc2).

**Comment by vietj** [comment]
I'm back porting to 3.9
