### ISSUE TITLE
Authentication is required but no CredentialsProvider has been registered 

### ISSUE THREAD

**Issue by razzbee** [vert-x3/vertx-config#83]
The Git config store seems not to work with bitbucket private repo, I have manually tested the repo with jGit and it works great, but does not work with vertx 

config: 
JsonObject()
        .put("url", "https://username@bitbucket.org/username/repo.git")
        .put("path", "local")
         .put("user","user")
         .put("password","password")
        .put("filesets",
            new JsonArray().add(new JsonObject().put("pattern", "*.json")))
);

**Comment by SGjorge** [comment]
Hello,

I've got the same issue, can you solve it? 

Thanks!

**Comment by razzbee** [comment]
I am using a thirdparty library to load content, parsing json and feeding it as json to the config Object

**Comment by SINGS079** [comment]
I can take a look at this issue. Is it specifically with bitbucket or have you experienced it with GitHub and GitLab too?

**Comment by ClaudenirFreitas** [comment]
Hi @razzbee @SGjorge , this bug has been fixed in commit: https://github.com/vert-x3/vertx-config/commit/b8e7a4a50695894d3816c49f651ffa96ac188353#diff-e3544bb9aad726e9dd8d0f429a1316e3

Is it posible to test on the new version (4.0.0-milestone3)?

**Comment by razzbee** [comment]
I will do some tests and post the results here.

**Comment by vietj** [comment]
thanks @razzbee

**Comment by vietj** [comment]
do we need to backport this bug in 3.8.2 ?
