### ISSUE TITLE
Be able to load configuration after packaging as jar.

### ISSUE THREAD

**Issue by CameronHudson8** [vert-x3/vertx-config#98]
This is a feature request.

Although locating the configuration at `src/main/resources/conf/config.json`, allows the configuration to be read before packaging, the configuration cannot be read after packaging.

When reading of the configuration is attempted after packaging, it results in
```
Camerons-Air:webservice cameronhudson$ java -jar target/webservice-1.0.0-SNAPSHOT.jar 
Oct 13, 2019 3:26:20 PM io.vertx.config.impl.ConfigRetrieverImpl
INFO: Config file path: conf/config.json, format:json
Oct 13, 2019 3:26:21 PM edu.cmu.dramaticstorm.App lambda$null$1
INFO: Listening on port 8080. // This is my own logger call.
Oct 13, 2019 3:26:21 PM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
INFO: Succeeded in deploying verticle
Oct 13, 2019 3:26:26 PM io.vertx.config.impl.ConfigRetrieverImpl
INFO: Config file path: conf/config.json, format:json
Oct 13, 2019 3:26:26 PM ConfigurationProvider#io.vertx.config.impl.spi.FileConfigStore@2e210e63
WARNING: Unable to process the retrieve the configuration null
```
And the application hangs.

**Comment by vietj** [comment]
do you mean that the config retriever should look at the classpath for the config file ?

**Comment by vietj** [comment]
what do you think @cescoffier ?

**Comment by CameronHudson8** [comment]
Perhaps. To be honest, I don't understand how Java maps resources and classpaths into the jar when packaging. However, reading a resource file packaged in a jar can be done with `Thread.currentThread().getContextClassLoader().getResourceAsStream(String filepath)`.

**Comment by vietj** [comment]
actually it is possible if you don't use the default path and configure it from System property _vertx-config-path_. So setting the system property _vertx-config-path_ to _conf/config.json_ should work. I'll contribute so it works in the general case.

**Comment by CameronHudson8** [comment]
Actually, I've since found that I get the aforementioned `WARNING` and hanging of the application whenever `ConfigRetriever.getConfig` is called inside a jar, regardless of whether the `conf/config.json` file is present at `src/main/resources` or elsewhere.

I've also tried:
- running the jar with `java -jar target/my-app.jar -conf src/main/resources/conf/config.json`,  but got the same `WARNING` and application hang. 
- Raising `conf/config.json` so that the `conf` directory is a sibling to `src`. While this also loads successfully when unpackaged, it also results in a `WARNING` and hang with `java -jar target/my-app.jar -conf conf/config.json`.
- Removing `conf/config.json` and `conf` completely, and running the jar as `java -jar target/my-app.jar` (without the `-conf`) flag, and it also results in the same `WARNING` and hang.

Now I'm wondering if this is perhaps a bug, or if there's something else wrong with my setup.

**Comment by vietj** [comment]
contributed https://github.com/vert-x3/vertx-config/issues/99

**Comment by vietj** [comment]
can you have a try with the contribution ?

**Comment by CameronHudson8** [comment]
I have to go to class now, but I will try that later today. Thanks for the quick update!

**Comment by CameronHudson8** [comment]
Here are the resulting logs. There are warnings about the thread being blocked. Although the reported config path is different from before, `ConfigurationProvider.get` still emits `WARNING: Unable to process the retrieve the configuration null` and the application hangs.

```
CCamerons-Air:webservice cameronhudson$ java -jar target/webservice-1.0.0-SNAPSHOT.jar 
Oct 14, 2019 9:17:18 AM io.vertx.config.impl.ConfigRetrieverImpl
INFO: Config file path: /var/folders/dr/j_n16l813t396y_jm6pcfqsm0000gn/T/vertx-cache/file-cache-1adc87a8-db9c-4651-8af4-4e2e9be1c995/conf/config.json, format:json
Oct 14, 2019 9:17:21 AM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main]=Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2737 ms, time limit is 2000 ms
Oct 14, 2019 9:17:22 AM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main]=Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3737 ms, time limit is 2000 ms
Oct 14, 2019 9:17:23 AM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main]=Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4742 ms, time limit is 2000 ms
Oct 14, 2019 9:17:24 AM edu.cmu.dramaticstorm.App lambda$null$1
INFO: Listening on port 8080.
Oct 14, 2019 9:17:24 AM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
INFO: Succeeded in deploying verticle

# HTTP requests that do not involve ConfigRetriever.getConfig work fine here.
# Sending an HTTP request that involves ConfigRetriever results in:

Oct 14, 2019 9:19:02 AM io.vertx.config.impl.ConfigRetrieverImpl
INFO: Config file path: /var/folders/dr/j_n16l813t396y_jm6pcfqsm0000gn/T/vertx-cache/file-cache-1adc87a8-db9c-4651-8af4-4e2e9be1c995/conf/config.json, format:json
Oct 14, 2019 9:19:02 AM ConfigurationProvider#io.vertx.config.impl.spi.FileConfigStore@bc8b4f7
WARNING: Unable to process the retrieve the configuration null
```

**Comment by Stwissel** [comment]
The issue happens because the result of `getFile()` once inside the jar looks like
`/some/external/path/yourjar.jar!/conf/config.json` and Java doesn't deal with the `!`
